### ISSUE TITLE
transistor use

### ISSUE THREAD

**Issue by rmeszes** [rmeszes/logarlec#89]
m?j. 04, 2024 5:34:12 DU. com.redvas.app.players.Player consoleAct
INFO: Choose command:
abort, Abort
use, Use item at given inventory item index
pickup, Pick item at given room item index
dispose, Dispose item at given inventory item index

m?j. 04, 2024 5:34:12 DU. com.redvas.app.players.Player consoleAct
FINE: Supply parameter:
m?j. 04, 2024 5:34:12 DU. com.redvas.app.players.Undergraduate useItem
FINE: Player 5 chose to use a(n) Transistor
m?j. 04, 2024 5:34:12 DU. com.redvas.app.players.Player consoleAct
FINE: Parameter is invalid
m?j. 04, 2024 5:34:12 DU. com.redvas.app.players.Player consoleAct
INFO: Choose command:

**Comment by o-l-c** [comment]
Megcsináltam, de nyitok egy új issue-t egy új hibára itt
